name: plantdensityanalysis_env
channels:
  - conda-forge
  - open3d-admin
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow
  - pyvista
  - joblib
  - tqdm
  - numba
  - scikit-learn
  - scipy
  - trimesh
  - rtree
  - matplotlib
  - ipykernel
  - dask
  - distributed
  - open3d
  - psutil
  - pip
  - pip:
      - fnvhash==0.1.0
      - tqdm_joblib
