name: plantdensityanalysis_env
channels:
  - conda-forge
  - open3d-admin
  - rios
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pyarrow
  - pyvista
  - joblib
  - tqdm
  - numba
  - scikit-learn
  - trimesh
  - networkx
  - rtree
  - ipykernel
  - dask
  - distributed
  - pip
  - joblib
  - loky
  - pip:
      - fnvhash==0.1.0
      - open3d
      - warp-lang
      - tqdm-joblib
