name: plantdensityanalysis_env
channels:
  - rios
  - open3d-admin
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - numpy
  - pandas
  - pyvista
  - joblib
  - open3d
  - tqdm
  - psutil
  - rtree
  - pip
  - pip:
      - trimesh[easy]
